[package]
name = "hello"
version = "1.0.0"
edition = "2021"
license = "MIT"
description = "rust lang book chapter 20"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]